### ISSUE TITLE
Other world chest don't work.

### ISSUE THREAD

**Issue by AndriassY** [Muqsit/ChestShop#16] opened 2017-03-12 10:46 UTC
The plugin gave problem to put or pick up items on normal chests... Because in the plugin it says

Set on null.

**Comment by Muqsit** [comment] 2017-03-12 11:04
Closing due to minimal information.

**Closed by Muqsit** 2017-03-12 11:04 UTC

**Comment by corytortoise** [comment] 2017-03-17 15:11
I believe the issue is that he can't transfer items between normal chests because of the plugin.
https://forums.pmmp.io/threads/per-world-plugin.1431/#post-16011

**Comment by AndriassY** [comment] 2017-03-19 07:18
I've already do another issua with more info  :)
